/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#5B8DEF',
        'primary-light': '#7BA3F0',
        'primary-dark': '#4A7AD9',
        'background-dark': '#0F0F0F',
        'background-soft': '#1A1A1A',
        'surface-dark': '#1F1F1F',
        'surface-soft': '#252525',
        'surface-border': '#2F2F2F',
        'surface-border-soft': '#3A3A3A',
        'text-dim': '#9A9A9A',
        'text-soft': '#B5B5B5',
      },
      fontFamily: {
        'display': ['-apple-system', 'BlinkMacSystemFont', 'Segoe UI', 'Roboto', 'Helvetica Neue', 'Arial', 'sans-serif'],
        'mono': ['ui-monospace', 'SFMono-Regular', 'Menlo', 'Monaco', 'Consolas', 'monospace'],
      },
      borderRadius: {
        'soft': '2rem',
        'softer': '2.5rem',
        'softest': '3rem',
        'pill': '9999px',
      },
      letterSpacing: {
        'tighter-soft': '-0.02em',
        'tight-soft': '-0.01em',
        'normal-soft': '0',
        'wide-soft': '0.01em',
        'wider-soft': '0.02em',
      },
      lineHeight: {
        'relaxed-soft': '1.75',
        'loose-soft': '2',
      },
      boxShadow: {
        'soft': '0 4px 20px -4px rgba(0, 0, 0, 0.3)',
        'soft-lg': '0 8px 30px -6px rgba(0, 0, 0, 0.4)',
        'glow-soft': '0 0 30px -8px rgba(91, 141, 239, 0.2)',
        'glow-soft-hover': '0 0 40px -8px rgba(91, 141, 239, 0.3)',
      },
      backdropBlur: {
        'soft': '12px',
      },
    },
  },
  plugins: [],
  safelist: [
    'text-text-dim',
    'text-text-soft',
    'border-surface-border',
    'border-surface-border-soft',
    'bg-surface-border',
    'bg-surface-dark',
    'bg-surface-soft',
    'bg-background-dark',
    'bg-background-soft',
    'text-primary',
    'text-primary-light',
    'bg-primary',
    'border-primary',
    'rounded-soft',
    'rounded-softer',
    'rounded-softest',
    'shadow-soft',
    'shadow-soft-lg',
    'backdrop-blur-soft',
  ],
}

